### ISSUE TITLE
DB method 에러 시에 status 404 (?)

### ISSUE THREAD

**Issue by tastekim** [Thorjuri/w7_clone_BE#5]
# Error log
## 1. 404 Not found Error
![스크린샷 2022-10-29 오전 12 50 20](https://user-images.githubusercontent.com/112174727/198682532-2991c5d2-f21a-424b-ab93-12dcb5bb37ed.png)
- 문제는 콘솔에도 에러가 안뜨고 서버도 꺼지지 않는다. 404 면 경로에러로 알고 있는데 라우터들이 다 연결 되어서 진행이 되다가도 db method 부분에서 실행이 안되면서 그냥 끊겨버린다. 

## 2. raw query??
![스크린샷 2022-10-29 오전 12 48 43](https://user-images.githubusercontent.com/112174727/198685365-213b8ad8-3eb0-4799-bdde-0bd48a124427.png)
- `Support for '{where : postId, userId}' has been removed.` 라는 에러메세지가 뜬다.

**Comment by tastekim** [comment]
# Solved
1. 애초에 경로 문제는 아니였고 method 내에서 조건을 양식에 맞지 않게 넣었던 것이 문제가 됬다. 저때 당시 코드가
```javascript
const option = {where: postId, userId}

await Likes.findOne(option)
```
이런 식으로 `method` 내에 조건을 변수에 담아서 전달했었을 때 1번 에러가 떴었는데 지금 보니 조건 내용이 잘못되있었고 그 상태로 전달하니 404 에러가 뜬 것 같다.(근데 애초에 경로문제가 아닌데 404를 뱉는것 자체가 이해가 안되는데 일단 해결,,,)

2. `sequelize method` 에서 `findOne, create, destroy` 등 안에 들어가는 내용이 조금씩 달랐는데 전부다 option 안에 같은 내용으로 조건을 넣어서 실행해서 나온 오류였다. 각 `method`에 맞게 바꿔주고 나니 잘 작동한다.

**Comment by Thorjuri** [comment]
postId, userId 를 중괄호로 한 번 더 감싸줘야 하는거 아닐까요??
일반적으로 sequelize method는 .findOnd({ where : { .. } }) 라고 알고 있어서요~~

**Comment by tastekim** [comment]
1번에서 말씀대로 중괄호로 묶으니까 해결됬습니다~! 근데 서버 내부에서 에러를 뱉는게 아니라 그냥 404 를 뱉는게 너무 이해가 안되네요 지금도,,,,
